# Site settings
title: Welcome to Ruby Lazy Log
email: hoanghiep.stt@gmail.com
description: Ruby on Rails Log
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ruby-log.github.io" # the base hostname & protocol for your site
twitter_username: tlmacon10
github_username:  hoanghiep.90

# Build settings
markdown: kramdown
